import Script from "next/script";
import "./globals.css";

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        {children}
        {/* <Script src="https://checkout.razorpay.com/v1/checkout.js" /> */}
      </body>
    </html>
  );
}
